apiVersion: v1
kind: Service
metadata:
  name: shopping_cart
  labels:
    app: shopping_cart
spec:
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: shopping_cart
  type: ClusterIP
