# Generated by Django 5.2.3 on 2026-05-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='panier',
            name='unique_cart_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='panier',
            name='unique_cart_per_cart',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='cart_token',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='session_key',
        ),
    ]
